- name: 'Despliegue de aplicación en AKS'
  hosts: localhost
  
  vars_files:
    - vars/vars.yaml

  tasks:
    - name: 'Definir los objectos deployment y servicios'
      template:
        src: templates/stateless.j2
        dest: "{{ directorio_trabajo }}/{{ aplicacion.definicion }}"

    - name: 'Crear el namespace de trabajo'
      kubernetes.core.k8s:
        kind: Namespace
        #name: "{{ k8s_namespace }}"
        state: present
        api_version: v1

    # - name: 'Crear Deployments y servicios de la aplicación'
      # kubernetes.core.k8s:
        # state: present
        # template: "{{ directorio_trabajo }}/{{ aplicacion.definicion }}"
